### ISSUE TITLE
Support for OS X builds in Godot 3.3+

### ISSUE THREAD

**Issue by RKelln** [firebelley/godot-export#58]
I just ran into this issue: https://github.com/godotengine/godot/issues/48076

As I understand it, exporting to MacOS requires the export to be done by MacOS. When looking up how to do github actions, I found this project, which looks great but would be very handy for it to support MacOS builds gracefully to make this problem much easier to deal with for opensource projects who don't have a MacOS machine.

I referenced this example in make my test workflow:
https://github.com/robpc/maze-test-game/blob/osx-test/.github/workflows/release-macos.yml

Mine (untested):
https://github.com/RKelln/godot-boids-acceleration-structure/blob/jackson/.github/workflows/release-macos.yml

**Comment by knightofiam** [comment]
This is a Godot issue that is already being worked on (see [this comment](https://github.com/godotengine/godot/issues/48076#issuecomment-898283111)). This GitHub Action builds macOS executables just fine; they just aren't signed. You can still run it by first removing the quarantine flag with:

```
sudo xattr -rd com.apple.quarantine MyCoolGodotGame.app
```

Not ideal, but it's the best workaround for now. This issue should be closed because it's a known bug in Godot and nothing can be done about it within the scope of this project.

**Comment by knightofiam** [comment]
In the meantime, vote for this pull request: https://github.com/godotengine/godot/pull/51550.

**Comment by firebelley** [comment]
Great, thank you for the info! I will close this 👍
