### ISSUE TITLE
Obtain new release version after export

### ISSUE THREAD

**Issue by raffomania** [firebelley/godot-export#67]
I'm uploading my game to itch.io after running the export action and would like to pass the newly released version to itch.io as well. Could you add an output to the action containing the new version?

**Comment by firebelley** [comment]
Hi! Can you please elaborate on your requirements? Does the output need to be an artifact or a file path? More context about your needs would be helpful in planning an enhancement.

**Comment by raffomania** [comment]
Thanks for your answer. I'm using the [butler push](https://github.com/marketplace/actions/butler-push) action specifically, which can take either a `VERSION` environment variable or a `VERSION_FILE` pointing to a file, so both would be possible.

My first intuition was that you could use the `output` [metadata section](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs), however I'm not sure how the actual setting of outputs in JS would work.

**Comment by firebelley** [comment]
Now that this action has been stripped down with v4.0.0, I believe that this issue is best solved with extra custom workflow steps, rather than including as functionality here. This action no longer creates releases, it simply builds the project and leaves it up to the workflow author to decide what to do with the resulting files.
